version: "3"
services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: ./docker/mariadb/Dockerfile
    restart: always
    volumes:
      - "./docker/mariadb/data:/var/lib/mysql"
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=python_db
      - TZ=Asia/Tokyo
